# Generated by Django 5.2.4 on 2025-07-21 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_funcionario_departamento_funcionario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_fim_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Publicação'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_inicio_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
