# Generated by Django 5.2.4 on 2025-07-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_funcionario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
