# Generated by Django 5.2.4 on 2025-07-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_funcionario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='api_funcionario',
        ),
    ]
