# Generated by Django 5.2.4 on 2025-07-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_funcionario_cargo_funcionario_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='setor',
            new_name='setor',
        ),
    ]
